# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

HALF_WIDTH = SCREEN_WIDTH/2
HALF_HEIGHT = SCREEN_HEIGHT/2

TOP_BOUNDARY = HALF_HEIGHT
BOT_BOUNDARY = -HALF_HEIGHT
LEFT_BOUNDARY = -HALF_WIDTH
RIGHT_BOUNDARY = HALF_WIDTH

BACKGROUND_COLOR = "purple"

HEAD_NORTH = 90
HEAD_SOUTH = 270
HEAD_LEFT = 180
HEAD_RIGHT = 0

# Paddle settings
PADDLE_STEP = 20
LEFT_PADDLE_XCOR = LEFT_BOUNDARY + 12
RIGHT_PADDLE_XCOR = RIGHT_BOUNDARY - 20

# ScoreBoard settings
SCOREBOARD_ALIGNMENT = "center"
SCOREBOARD_FONT = ("consolas", 24, "normal")

LEFT_SCOREBOARD_XCOR = LEFT_BOUNDARY//2
LEFT_SCOREBOARD_YCOR = TOP_BOUNDARY - 50
RIGHT_SCOREBOARD_XCOR = RIGHT_BOUNDARY//2
RIGHT_SCOREBOARD_YCOR = LEFT_SCOREBOARD_YCOR

# Ball settings
BALL_COLOR = "red"

# Middle-line
MIDDLE_LINE_COLOR = "yellow"
MIDDLE_LINE_SIZE = 5