# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

HALF_WIDTH = SCREEN_WIDTH/2
HALF_HEIGHT = SCREEN_HEIGHT/2

TOP_BOUNDARY = HALF_HEIGHT
BOT_BOUNDARY = -HALF_HEIGHT
LEFT_BOUNDARY = -HALF_WIDTH
RIGHT_BOUNDARY = HALF_WIDTH

BACKGROUND_COLOR = "purple"

HEAD_NORTH = 90
HEAD_SOUTH = 270
HEAD_LEFT = 180
HEAD_RIGHT = 0

# Paddle settings
PADDLE_STEP = 40
LEFT_PADDLE_XCOR = LEFT_BOUNDARY + 12
LEFT_PADDLE_START_CORD = (LEFT_PADDLE_XCOR, 0)

RIGHT_PADDLE_XCOR = RIGHT_BOUNDARY - 20
RIGHT_PADDLE_START_CORD = (RIGHT_PADDLE_XCOR, 0)

# ScoreBoard settings
SCOREBOARD_ALIGNMENT = "center"
SCOREBOARD_FONT = ("consolas", 24, "normal")

LEFT_SCOREBOARD_XCOR = LEFT_BOUNDARY//2
LEFT_SCOREBOARD_YCOR = TOP_BOUNDARY - 50
LEFT_SCOREBOARD_CORD = (LEFT_SCOREBOARD_XCOR, LEFT_SCOREBOARD_YCOR)

RIGHT_SCOREBOARD_XCOR = RIGHT_BOUNDARY//2
RIGHT_SCOREBOARD_YCOR = LEFT_SCOREBOARD_YCOR
RIGHT_SCOREBOARD_CORD = (RIGHT_SCOREBOARD_XCOR, RIGHT_SCOREBOARD_YCOR)

# Ball settings
BALL_COLOR = "red"
DEFAULT_BALL_SPEED = 0.05
SPEED_INCREASE_RATE = 0.95